# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "t2WHgz6WsOX7M3LFArHJ3wId2t6CetimM1tlKsimTjqRtI2pPdFitzgCSHGY0qHg9fVEOlPLzk929qvTyNg9ZfOMT4BlwKUmSW3qgq62umTV2jKI2b+v1wfEfIdUkGNpkVqsc2G5vN69lsmWekPJtrWsrHY12dlzSTKjYve+VbPHaddrSb2ICqBAKsFed8kdJXaE4K66iMYXa7FK71wCjVTcLaM0Z6C9uMM+C3cehm+wr6MBYOHKntwkGcwsj75jeTTx/dFWBJQbzPbevV8t+LlvUAe1F2R5bLdl3Z7HDbN2z63hLhv8S5mXjhJBNJq6aosBPIBwLHam5GfovdJxFmNjzNvceRYBgkIslL34ppGDTrHFJBXmG/3xOO2Me0AuIcOmfSrCAx0E8hI6dXRyLtmR4wqo31rDgoj98aeUE3EnWdOFqbmDod1B0QF4apzFD9hLMEgkI276B45Uld4ZGtvs97nrG1Y/5RckqB7Zipv6K+DgDxnfyAewS7FB5MB2y3owqYP1PpkZzjrYf8AP3DvRqlRa4kRRWO0fKLzKrMkHsSTrHnziY/cLBCjuYnO33HcUus4x1/vHIuKTrU/mckfwIC4CysSFdjROebukTBpgo3eBGdtHv/lvRjP9VGHis4P+zHGv6eRPQ4cq2yZejRp8CHjegisd6MlU30ojUtU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
