travis:
  secure:
    BINSTAR_TOKEN: Cf2mK+ql2nK/DDaE+EkIkQl98aWvtyoUGBvnebL3XVvQ1tWeTDfKakQnr+2BflceiCZSnQoyZtiUMtwcISb6VuOFkE6zlUCev2YXxRNWDH5KVi5XP4VlFZE4HznXHXGMUuk3x/JJexDvsdEiYqAwh9q/ufKVt33kWsXV9ncJPqTAOCShsYtas7pibIXZXTTDKNtX64uJVXu+Of/XH2krFNmqclIZgQOgLxQ1IT+sDBKdfcvlpz0o5L8+j+s+S+D9F+yweojPMMTgDtAHw5KTcHcxzaqEAl4MYxyP99+wjFTkE6uOS1F1CIFJzzU/7jKt3HIiWDVzfYimot6ZRs54o4mgTIosnvYDm/ol4Z+16WUVYDnQKFGj2Fo9b9PrQY2kZ1f0idafcH5o3d8xYIYuWQ1lmUFBvNrxeQNWbSCzWuTuMLJ4ioWTN7lil+Egm8LHByQjOSZyNbi8ZoZqdz9dChnFVSoiyDnXz4nJ8cqUEDCV/9VcfyY9lM9y2RTegmWlAwu8IRQ9Xzl1vS0WiMkOiQR/KdI5L5DIr2nlrCOQ1m38z8uFz6NSd16l7rhvAwBb9+aTQFjVO8veUfrl2z+9TXv/bdDesrqOBF0cqsRCtGsbS62K4atYYy+4Ct1gjplAEJceGWEeywfrDLZivrOKszN1ZPmY1ArrbV59JFM7R3Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
